name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
    
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build Changes
      run: dotnet build
    - name: Test Changes
      run: dotnet test --no-build --verbosity normal  
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
        role-session-name: GitHub-Action-Role
        aws-region: us-east-2
    - run: |
        echo "Deploying"
        commit_hash=`git rev-parse HEAD`
        aws deploy create-deployment --application-name record-rack --deployment-group-name record-rack_deployment --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures --region us-east-2
      
    
