name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build Changes
      run: dotnet build
    - name: Test Changes
      run: dotnet test --no-build --verbosity normal
      
#  deploy:
#    name: Deploy to AWS
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
      
    
